### ISSUE TITLE
fails to install on OS X 10.12 Sierra

### ISSUE THREAD

**Issue by thibaultcha** [lunarmodules/luasystem#3]
Hey there,

Installing luasystem on OS X 10.12 gives the following:

```
$ luarocks install luasystem
Installing https://luarocks.org/luasystem-0.2.0-0.src.rock
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/core.c -o src/core.o
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/compat.c -o src/compat.o
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/time.c -o src/time.o
In file included from src/time.c:14:
src/time_osx.h:20:9: warning: 'CLOCK_REALTIME' macro redefined [-Wmacro-redefined]
#define CLOCK_REALTIME  0
        ^
/usr/include/time.h:154:9: note: previous definition is here
#define CLOCK_REALTIME _CLOCK_REALTIME
        ^
In file included from src/time.c:14:
src/time_osx.h:23:9: warning: 'CLOCK_MONOTONIC' macro redefined [-Wmacro-redefined]
#define CLOCK_MONOTONIC 3
        ^
/usr/include/time.h:156:9: note: previous definition is here
#define CLOCK_MONOTONIC _CLOCK_MONOTONIC
        ^
In file included from src/time.c:14:
src/time_osx.h:36:12: error: static declaration of 'clock_gettime' follows non-static declaration
static int clock_gettime(int clockid, struct timespec *ts) {
           ^
/usr/include/time.h:177:5: note: previous declaration is here
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
    ^
2 warnings and 1 error generated.

Error: Build error: Failed compiling object src/time.o
```

This thus prevents the installation of `busted`, which depends on luasystem. Some more info:

```
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12
BuildVersion:   16A323
```

**Comment by thibaultcha** [comment]
I can submit a patch but not sure how you would like to prefix those (I suppose)?

**Comment by o-lim** [comment]
I believe this is fixed in PR #2

**Comment by o-lim** [comment]
Try the latest master branch.  If everything works for you, then I'll make a new release with the fix.

**Comment by thibaultcha** [comment]
The latest master branch is still failing with the exact same result for me. Not sure if it is the fix or an issue on my side, as I'm using Xcode 8 with the latest developers tools linked to it.

**Comment by o-lim** [comment]
Sorry, I don't have access to a mac to test this on.  Can you try adding this to the begining of time.c?
```c
#ifdef __APPLE__
  #include <AvailabilityMacros.h>
  #ifndef MAC_OS_X_VERSION_10_12
    #define MAC_OS_X_VERSION_10_12 101200
  #endif
#endif

#define HAVE_CLOCK_GETTIME   defined(__APPLE__) && MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_12
```

**Comment by o-lim** [comment]
Please also change
```c
#ifndef HAVE_CLOCK_GETTIME
```
to
```c
#if !(HAVE_CLOCK_GETTIME)
```

**Comment by thibaultcha** [comment]
No success with those either. I will investigate further once I have some time on my hands. Would love for other folks to give master a try, as I'm not sure where the problem could be coming from at this point.

**Comment by o-lim** [comment]
The problem is actually very simple. Basically, `HAVE_CLOCK_GETTIME` is not defined, which means you need to manually define it or update the code to define it based on the version of OSX.  This is what I was trying to you do with the above changes, but I have no way of testing whether or not it works.

**Comment by thibaultcha** [comment]
Correction: I totally get what the issue is, what I mean is that I don't know why I don't have those defined when I compile the project :sweat_smile: just wondering if I have my compiler/Xcode tools properly setup since I updated to 10.12.

**Comment by o-lim** [comment]
Can you try compiling the changes with just luarocks or just gcc?  I don't think `HAVE_CLOCK_GETTIME` is defined by OSX at all, but I think `<AvailabilityMacros.h>` should be in the include path.

You can also try the following with just `gcc main.c`
```c
#include <stdio.h>

#if __APPLE__
#include <AvailabilityMacros.h>
#ifndef MAC_OS_X_VERSION_10_12
#define MAC_OS_X_VERSION_10_12 101200
#endif
#endif

int main(int argc, const char * argv[]) {
#if MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_11
    printf("10.11\n");
#endif
#if MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_12
    printf("10.12\n");
#endif
    return 0;
}
```
If `gcc main.c` works, then I can update the master branch with the appropriate fix.

See also civetweb/civetweb#349

**Comment by hugomd** [comment]
Has this been fixed? I'm having the same issue

**Comment by o-lim** [comment]
Can you try the latest master branch?  If it works for you, then I'll make a new release with the fix.

**Comment by hugomd** [comment]
@o-lim If you can tell me how to build it.. At the moment I'm running `make` with output:
```bash
➜  luasystem (master) ✔ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src macosx
/Applications/Xcode.app/Contents/Developer/usr/bin/make all PLAT=macosx
gcc  -I/opt/local/include/lua/2.1  -Wall -O2 -fno-common -fvisibility=hidden   -c -o core.o core.c
core.c:1:10: fatal error: 'lua.h' file not found
#include <lua.h>
         ^
1 error generated.
make[2]: *** [core.o] Error 1
make[1]: *** [macosx] Error 2
make: *** [macosx] Error 2
➜  luasystem (master) ✔
```

**Comment by o-lim** [comment]
Just use luarocks to build and install
```
luarocks make luasystem-scm-0.rockspec
```

**Comment by hugomd** [comment]
@o-lim Still seems to be failing:
```Bash
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/core.c -o src/core.o
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/compat.c -o src/compat.o
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/time.c -o src/time.o
In file included from src/time.c:23:
src/time_osx.h:20:9: warning: 'CLOCK_REALTIME' macro redefined [-Wmacro-redefined]
#define CLOCK_REALTIME  0
        ^
/usr/include/time.h:154:9: note: previous definition is here
#define CLOCK_REALTIME _CLOCK_REALTIME
        ^
In file included from src/time.c:23:
src/time_osx.h:23:9: warning: 'CLOCK_MONOTONIC' macro redefined [-Wmacro-redefined]
#define CLOCK_MONOTONIC 3
        ^
/usr/include/time.h:156:9: note: previous definition is here
#define CLOCK_MONOTONIC _CLOCK_MONOTONIC
        ^
In file included from src/time.c:23:
src/time_osx.h:36:12: error: static declaration of 'clock_gettime' follows non-static declaration
static int clock_gettime(int clockid, struct timespec *ts) {
           ^
/usr/include/time.h:177:5: note: previous declaration is here
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
    ^
2 warnings and 1 error generated.

Error: Build error: Failed compiling object src/time.o
```

**Comment by o-lim** [comment]
It looks like your MACOSX_DEPLOYMENT_TARGET environment variable is being set to 10.8 instead of 10.12.  Looking at the luarocks source code, it looks like luarocks maxes out at 10.8 for some reason.  Can you copy paste the contents of /usr/include/time.h?

**Comment by hugomd** [comment]
@o-lim Here you go:

```C
/*
 * Copyright (c) 2000 Apple Computer, Inc. All rights reserved.
 *
 * @APPLE_LICENSE_HEADER_START@
 * 
 * This file contains Original Code and/or Modifications of Original Code
 * as defined in and that are subject to the Apple Public Source License
 * Version 2.0 (the 'License'). You may not use this file except in
 * compliance with the License. Please obtain a copy of the License at
 * http://www.opensource.apple.com/apsl/ and read it before using this
 * file.
 * 
 * The Original Code and all software distributed under the License are
 * distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 * EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 * INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
 * Please see the License for the specific language governing rights and
 * limitations under the License.
 * 
 * @APPLE_LICENSE_HEADER_END@
 */
/*
 * Copyright (c) 1989, 1993
 *	The Regents of the University of California.  All rights reserved.
 * (c) UNIX System Laboratories, Inc.
 * All or some portions of this file are derived from material licensed
 * to the University of California by American Telephone and Telegraph
 * Co. or Unix System Laboratories, Inc. and are reproduced herein with
 * the permission of UNIX System Laboratories, Inc.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *	This product includes software developed by the University of
 *	California, Berkeley and its contributors.
 * 4. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 *	@(#)time.h	8.3 (Berkeley) 1/21/94
 */

#ifndef _TIME_H_
#define	_TIME_H_

#include <_types.h>
#include <Availability.h>
#include <sys/_types/_clock_t.h>
#include <sys/_types/_null.h>
#include <sys/_types/_size_t.h>
#include <sys/_types/_time_t.h>
#include <sys/_types/_timespec.h>

struct tm {
	int	tm_sec;		/* seconds after the minute [0-60] */
	int	tm_min;		/* minutes after the hour [0-59] */
	int	tm_hour;	/* hours since midnight [0-23] */
	int	tm_mday;	/* day of the month [1-31] */
	int	tm_mon;		/* months since January [0-11] */
	int	tm_year;	/* years since 1900 */
	int	tm_wday;	/* days since Sunday [0-6] */
	int	tm_yday;	/* days since January 1 [0-365] */
	int	tm_isdst;	/* Daylight Savings Time flag */
	long	tm_gmtoff;	/* offset from CUT in seconds */
	char	*tm_zone;	/* timezone abbreviation */
};

#if __DARWIN_UNIX03
#define CLOCKS_PER_SEC  1000000	/* [XSI] */
#else /* !__DARWIN_UNIX03 */
#include <machine/_limits.h>	/* Include file containing CLK_TCK. */

#define CLOCKS_PER_SEC  (__DARWIN_CLK_TCK)
#endif /* __DARWIN_UNIX03 */

#ifndef _ANSI_SOURCE
extern char *tzname[];
#endif

extern int getdate_err;
#if __DARWIN_UNIX03
extern long timezone __DARWIN_ALIAS(timezone);
#endif /* __DARWIN_UNIX03 */
extern int daylight;

__BEGIN_DECLS
char *asctime(const struct tm *);
clock_t clock(void) __DARWIN_ALIAS(clock);
char *ctime(const time_t *);
double difftime(time_t, time_t);
struct tm *getdate(const char *);
struct tm *gmtime(const time_t *);
struct tm *localtime(const time_t *);
time_t mktime(struct tm *) __DARWIN_ALIAS(mktime);
size_t strftime(char * __restrict, size_t, const char * __restrict, const struct tm * __restrict) __DARWIN_ALIAS(strftime);
char *strptime(const char * __restrict, const char * __restrict, struct tm * __restrict) __DARWIN_ALIAS(strptime);
time_t time(time_t *);

#ifndef _ANSI_SOURCE
void tzset(void);
#endif /* not ANSI */

/* [TSF] Thread safe functions */
char *asctime_r(const struct tm * __restrict, char * __restrict);
char *ctime_r(const time_t *, char *);
struct tm *gmtime_r(const time_t * __restrict, struct tm * __restrict);
struct tm *localtime_r(const time_t * __restrict, struct tm * __restrict);

#if !defined(_ANSI_SOURCE) && (!defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE))
time_t posix2time(time_t);
#if !__DARWIN_UNIX03
char *timezone(int, int);
#endif /* !__DARWIN_UNIX03 */
void tzsetwall(void);
time_t time2posix(time_t);
time_t timelocal(struct tm * const);
time_t timegm(struct tm * const);
#endif /* neither ANSI nor POSIX */

#if !defined(_ANSI_SOURCE)
int nanosleep(const struct timespec *__rqtp, struct timespec *__rmtp) __DARWIN_ALIAS_C(nanosleep);
#endif

#if !defined(_DARWIN_FEATURE_CLOCK_GETTIME) || _DARWIN_FEATURE_CLOCK_GETTIME != 0
#if __DARWIN_C_LEVEL >= 199309L
#if __has_feature(enumerator_attributes)
#define __CLOCK_AVAILABILITY __OSX_AVAILABLE(10.12) __IOS_AVAILABLE(10.0) __TVOS_AVAILABLE(10.0) __WATCHOS_AVAILABLE(3.0)
#else
#define __CLOCK_AVAILABILITY
#endif

typedef enum {
_CLOCK_REALTIME __CLOCK_AVAILABILITY = 0,
#define CLOCK_REALTIME _CLOCK_REALTIME
_CLOCK_MONOTONIC __CLOCK_AVAILABILITY = 6,
#define CLOCK_MONOTONIC _CLOCK_MONOTONIC
#if !defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE)
_CLOCK_MONOTONIC_RAW __CLOCK_AVAILABILITY = 4,
#define CLOCK_MONOTONIC_RAW _CLOCK_MONOTONIC_RAW
_CLOCK_MONOTONIC_RAW_APPROX __CLOCK_AVAILABILITY = 5,
#define CLOCK_MONOTONIC_RAW_APPROX _CLOCK_MONOTONIC_RAW_APPROX
_CLOCK_UPTIME_RAW __CLOCK_AVAILABILITY = 8,
#define CLOCK_UPTIME_RAW _CLOCK_UPTIME_RAW
_CLOCK_UPTIME_RAW_APPROX __CLOCK_AVAILABILITY = 9,
#define CLOCK_UPTIME_RAW_APPROX _CLOCK_UPTIME_RAW_APPROX
#endif
_CLOCK_PROCESS_CPUTIME_ID __CLOCK_AVAILABILITY = 12,
#define CLOCK_PROCESS_CPUTIME_ID _CLOCK_PROCESS_CPUTIME_ID
_CLOCK_THREAD_CPUTIME_ID __CLOCK_AVAILABILITY = 16
#define CLOCK_THREAD_CPUTIME_ID _CLOCK_THREAD_CPUTIME_ID
} clockid_t;

__CLOCK_AVAILABILITY
int clock_getres(clockid_t __clock_id, struct timespec *__res);

__CLOCK_AVAILABILITY
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);

#if !defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE)
__CLOCK_AVAILABILITY
__uint64_t clock_gettime_nsec_np(clockid_t __clock_id);
#endif

__OSX_AVAILABLE(10.12) __IOS_PROHIBITED
__TVOS_PROHIBITED __WATCHOS_PROHIBITED
int clock_settime(clockid_t __clock_id, const struct timespec *__tp);

#undef __CLOCK_AVAILABILITY
#endif /* __DARWIN_C_LEVEL */
#endif /* _DARWIN_FEATURE_CLOCK_GETTIME */

__END_DECLS

#ifdef _USE_EXTENDED_LOCALES_
#include <xlocale/_time.h>
#endif /* _USE_EXTENDED_LOCALES_ */

#endif /* !_TIME_H_ */
```

**Comment by o-lim** [comment]
@hugomd I made an update.  Can you try again with the latest master branch?

**Comment by hugomd** [comment]
Similar issue I'm afraid @o-lim:

```Bash
➜  luasystem (master) ✔ luarocks make luasystem-scm-0.rockspec
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/core.c -o src/core.o
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/compat.c -o src/compat.o
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/Cellar/luajit/2.1_1/include/luajit-2.1 -c src/time.c -o src/time.o
In file included from src/time.c:23:
src/time_osx.h:20:9: warning: 'CLOCK_REALTIME' macro redefined [-Wmacro-redefined]
#define CLOCK_REALTIME  0
        ^
/usr/include/time.h:154:9: note: previous definition is here
#define CLOCK_REALTIME _CLOCK_REALTIME
        ^
In file included from src/time.c:23:
src/time_osx.h:23:9: warning: 'CLOCK_MONOTONIC' macro redefined [-Wmacro-redefined]
#define CLOCK_MONOTONIC 3
        ^
/usr/include/time.h:156:9: note: previous definition is here
#define CLOCK_MONOTONIC _CLOCK_MONOTONIC
        ^
In file included from src/time.c:23:
src/time_osx.h:36:12: error: static declaration of 'clock_gettime' follows non-static declaration
static int clock_gettime(int clockid, struct timespec *ts) {
           ^
/usr/include/time.h:177:5: note: previous declaration is here
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
    ^
2 warnings and 1 error generated.

Error: Build error: Failed compiling object src/time.o
➜  luasystem (master) ✔
```

**Comment by o-lim** [comment]
@hugomd Can you try again?  I think it should work this time.

**Comment by hugomd** [comment]
@o-lim It builds now! 👍 Thanks!
